default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#host: 'localhost'

development:
  <<: *default
  database: project_development

test:
  <<: *default
  database: project_test

production:
  <<: *default
  database: project_production
  username: postgres
  password: 

